In [2]:
list = [10,20,30,40,50]
print("original list:",list)
## Add the element to the end of list
list.append(60)
print("after append(60):",list)
##Extends the list by appending all the items from an iterable
list.extend([70,80])
print(" after extend([70,80]):",list)   
##Inserts an element at a specified position
list.insert(1,15)
print("after insert(1,15):",list)
##Removes the first occurrence of a specified value
list.remove(50)
print("after remove(50):",list)
##Removes and returns the element at a specified index (or the last element if no index is given)
list.pop()
print("after pop():",list)
##Removes all elements from the list
list.clear()
print("after clear():",list)
list = [10, 20, 30, 40, 50]
print("original list:",list)
##Returns the index of the first occurrence of a value
index_40 = list.index(40)
print("index of (40):",index_40)
## Returns the number of times a specified value appears in the list
count_20 = list.count(20)
print("count of 20 in the list:",count_20)
##Sorts the list in ascending order
list.sort()
print("after sort():",list)
##Reverses the order of elements in the list
list.reverse()
print("after reverse():",list)


original list: [10, 20, 30, 40, 50]
after append(60): [10, 20, 30, 40, 50, 60]
 after extend([70,80]): [10, 20, 30, 40, 50, 60, 70, 80]
after insert(1,15): [10, 15, 20, 30, 40, 50, 60, 70, 80]
after remove(50): [10, 15, 20, 30, 40, 60, 70, 80]
after pop(): [10, 15, 20, 30, 40, 60, 70]
after clear(): []
original list: [10, 20, 30, 40, 50]
index of (40): 3
count of 20 in the list: 1
after sort(): [10, 20, 30, 40, 50]
after reverse(): [50, 40, 30, 20, 10]


In [22]:
# Create a tuple with 3 student names
students = ("priti", "Priya", "prachi")
print("Original Tuple:", students)
# Try changing the second name
try:
    # Attempt to change the second element
    students[1] = "Sneha"  
except TypeError as e:
    print("Error:", e)

Original Tuple: ('priti', 'Priya', 'prachi')
Error: 'tuple' object does not support item assignment


In [4]:
## create a set with same duplicate values
set = {25,10,55,25,75,10,55,75,30,90}
print("set_with_duplicates:",set)

set_with_duplicates: {90, 55, 25, 10, 75, 30}


In [6]:
## create a dictionary
person_info = {
    "name": "priti",
    "age":21,
    "city":"dharashiv",
}
## printing the original dictionary
print("original person_info:",person_info)
## update the age
person_info["age"]=22
## addind a new kay 'email'
person_info["email"] = "pritiyadake@gmail.com"
## print the final dictionary
print("updated dictionary:",person_info)

original person_info: {'name': 'priti', 'age': 21, 'city': 'dharashiv'}
updated dictionary: {'name': 'priti', 'age': 22, 'city': 'dharashiv', 'email': 'pritiyadake@gmail.com'}


In [13]:
## Take age as input from the user
age = int(input("enter your age"))
##check if the age is valid (not negative) 
if age < 0:
    print("age cannot be negative.please enter a valid age.")
##check for voting eligibility
elif age >= 18:
   print ("you are eligible to vote!")
else:
  years_to_wait = 18 - age
print("you are not eligible to vote yet.you need to wait {years_to_wait}more years.")
print("invalid input.please enter a numerical value for age.")

enter your age 17


you are not eligible to vote yet.you need to wait {years_to_wait}more years.
invalid input.please enter a numerical value for age.


In [5]:
## taking mark as input
marks = int(input("enter your marks:"))
##cheaking the grade using if-elif-else 
if marks>=90:
    print("grade:A")
elif marks >=75:
    print("grade:B")
elif marks >=50:
    print("grade:c")
else: 
    print("grade: fail")

enter your marks: 40


grade: fail


In [8]:
# Take input from user
num = int(input("Enter a number: "))
# Check conditions
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("It is also even.")
    else:
        print("It is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  8


The number is positive.
It is also even.


In [9]:
import numpy as np

# 1️ Scalar
scalar = np.array(5)
print("Scalar:\n", scalar)

# 2️ 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", array_1d)

# 3️ 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.arange(10, 70, 10).reshape(2, 3)
print("\n2D Array:\n", array_2d)

Scalar:
 5

1D Array:
 [1 2 3 4 5]

2D Array:
 [[10 20 30]
 [40 50 60]]


In [10]:
import numpy as np
# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

print("4x4 Random Integer Array:\n", random_array)

4x4 Random Integer Array:
 [[ 72  87  90  83]
 [ 30  36   2  63]
 [ 46   4  64  35]
 [ 86 100  13  37]]


In [11]:
import numpy as np
import pandas as pd

# Create a 2D NumPy array (3x3)
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60],
                     [70, 80, 90]])

# Convert to a DataFrame with column names
df = pd.DataFrame(array_2d, columns=['A', 'B', 'C'])

print("NumPy Array:\n", array_2d)
print("\nPandas DataFrame:\n", df)

NumPy Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Pandas DataFrame:
     A   B   C
0  10  20  30
1  40  50  60
2  70  80  90


In [15]:
import pandas as pd
import numpy as np
# Create a DataFrame manually with 10 rows
data = {
    'Name': ['Tanay', 'Priya', 'Tanishk', 'Sneha', 'Ravi', 'priti', 'Neha', 'Rutuja', 'Riya', 'samarth'],
    'Age': [25, 30, 22, 28, 26, 25, 27, 32, 29, 22],
    'City': ['Mumbai', 'Pune', 'Delhi', 'Chennai', 'Kolkata', 'Mumbai', 'Delhi', 'Pune', 'chennai', 'Delhi'],
    'Salary': [50000, 60000, np.nan , 58000, 62000, 50000, 55000,np.nan, 75000, 58000]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df)
#  Display info and statistics
print("\nDataFrame Info:")
print(df.info())
print("\nDescriptive Statistics:")
print(df.describe())
#  Select 'Name' and 'City' columns
print("\nSelected Columns (Name & City):\n", df[['Name', 'City']])
#  Drop 'City' column
df_dropped = df.drop(columns=['City'])
print("\nAfter Dropping 'City' Column:\n", df_dropped)
#  Fill missing Salary values with mean
df['Salary'].fillna(df['Salary'].mean(), inplace=True)
print("\nAfter Filling Missing Salary Values with Mean:\n", df)
# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\nAfter Removing Duplicate Rows:\n", df_no_duplicates)

Original DataFrame:
       Name  Age     City   Salary
0    Tanay   25   Mumbai  50000.0
1    Priya   30     Pune  60000.0
2  Tanishk   22    Delhi      NaN
3    Sneha   28  Chennai  58000.0
4     Ravi   26  Kolkata  62000.0
5    priti   25   Mumbai  50000.0
6     Neha   27    Delhi  55000.0
7   Rutuja   32     Pune      NaN
8     Riya   29  chennai  75000.0
9  samarth   22    Delhi  58000.0

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

Descriptive Statistics:
             Age        Salary
count  10.000000      8.000000
mean   26.600000  58500.000000
std     3.272783   7964.205637
min    22.000000  50000.000000
25%    25.000

C:\Users\Dell\AppData\Local\Temp\ipykernel_1448\2600311383.py:23: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(), inplace=True)
